# Generated by Django 3.2 on 2021-12-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    def insert_values_into_price_field(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        order_items = OrderItem.objects.select_related('product')

        for order_item in order_items:
            order_item.price = order_item.product.price

        OrderItem.objects.bulk_update(order_items, ['price', ])

    dependencies = [
        ('foodcartapp', '0041_add_field'),
    ]

    operations = [
        migrations.RunPython(insert_values_into_price_field,
                             reverse_code=migrations.RunPython.noop)
    ]
