# Generated by Django 3.2 on 2022-01-10 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_change_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='значение д.б. больше нуля')], verbose_name='кол-во'),
        ),
    ]
